new option --header <classname>, cosmetics

diff --git a/sogui-config.in b/sogui-config.in
--- a/sogui-config.in
+++ b/sogui-config.in
@@ -53,6 +53,7 @@ Options:
   --link <program> <object> [<object>]...
   --build <program> <sourcefile> [<sourcefile>]...
   --setup | --setup-front
+  --header <classname>
   --version
   --usage | --help"
 
@@ -79,226 +80,236 @@ fi
 while test $# -gt 0
 do
   case $1 in
-    --usage | --help)  echo "$usage"         ;;
-    --version)         echo "$version"       ;;
-    --cppflags)        echo "$cppflags"      ;;
-    --cflags)          echo "$cflags"        ;;
-    --cxxflags)        echo "$cxxflags"      ;;
-    --ldflags)         echo "$ldflags"       ;;
-    --libs)            echo "$libs"          ;;
-    --msvcrt)          echo "$msvcrt"        ;;
-    --datadir)         echo "$datadir"       ;;
-    --includedir)      echo "$includedir"    ;;
-    --frameworkdir)    echo "$frameworkdir"  ;;
-    --ac-subst)
-      shift
-      if test $# -eq 1; then
-        case $1 in
-          *\.in)
-            echo $me --ac-subst $1
-            outfile=`echo $1 | sed -e 's/\.in$//'`
-            sedscript=/tmp/ac_subst_$$.sed
-            grep "^AC_SUBST_" $configfile \
-              | sed -e 's/^AC_SUBST_\([^=]*\)="\([^"]*\)"$/s\/@\1@\/\2\/g;/g' \
-              >$sedscript
-            rm -f $outfile
-            case `echo "$compiler" | sed 's/ .*//g'` in
-            gcc | g++)
-              echo "# 1 \"$1\"" >$outfile
-              ;;
-            wrapmsvc | wrapmsvc.exe | msvccc)
-              echo "#line 1 \"$1\"" >$outfile
-              ;;
-            esac
-            sed -f $sedscript <$1 >>$outfile
-            rm -f $sedscript
-            ;;
-          *)
-            eval "VAL=\${AC_SUBST_$1}"
-            echo "$VAL"
-            ;;
+  --usage | --help)  echo "$usage"         ;;
+  --version)         echo "$version"       ;;
+  --cppflags)        echo "$cppflags"      ;;
+  --cflags)          echo "$cflags"        ;;
+  --cxxflags)        echo "$cxxflags"      ;;
+  --ldflags)         echo "$ldflags"       ;;
+  --libs)            echo "$libs"          ;;
+  --msvcrt)          echo "$msvcrt"        ;;
+  --datadir)         echo "$datadir"       ;;
+  --includedir)      echo "$includedir"    ;;
+  --frameworkdir)    echo "$frameworkdir"  ;;
+  --ac-subst)
+    shift
+    if test $# -eq 1; then
+      case $1 in
+      *\.in)
+        echo $me --ac-subst $1
+        outfile=`echo $1 | sed -e 's/\.in$//'`
+        sedscript=/tmp/ac_subst_$$.sed
+        grep "^AC_SUBST_" $configfile \
+          | sed -e 's/^AC_SUBST_\([^=]*\)="\([^"]*\)"$/s\/@\1@\/\2\/g;/g' \
+          >$sedscript
+        rm -f $outfile
+        case `echo "$compiler" | sed 's/ .*//g'` in
+        gcc | g++)
+          echo "# 1 \"$1\"" >$outfile
+          ;;
+        wrapmsvc | wrapmsvc.exe | msvccc)
+          echo "#line 1 \"$1\"" >$outfile
+          ;;
         esac
-      else
-        for arg in $@; do
-          $program --alternate="$alternate" --ac-subst $arg
-          retval=$?
-          test $retval -ne 0 && exit $retval
-        done
-      fi
-      exit 0
-      ;;
-    --ac-desubst)
-      shift
-      echo $me --ac-desubst $1
-      outfile="$1.in"
-      sedscript=/tmp/ac_subst_$$.sed
-      grep "^AC_SUBST_" $configfile \
-        | sed -e 's/^AC_SUBST_\([^=]*\)="\([^"]*\)"$/s\/\2\/@\1@\/g;/g' \
-        >$sedscript
-      sed -f $sedscript <$1 >$outfile
-      rm -f $sedscript
-      ;;
-    --compile)
-      shift
-      if test $# -eq 1; then
-        case $1 in
-          *\.in)
-            outfile=`echo $1 | sed -e 's/\.in$//'`
-            $program --alternate="$alternate" --ac-subst $1
-            $program --alternate="$alternate" --compile $outfile
-            retval=$?
-            test $retval -ne 0 && exit $retval
-            ;;
-          *)
-            basename=`echo "$1" | sed -e 's/\.[^\.]*$//'`  # strip off extension
-            echo $compiler $CPPFLAGS $cppflags $CXXFLAGS $cxxflags -c $1 -o $basename.@OBJEXT@ \
-              | $preformat | sed "$sedformat"
-            $compiler \
-              $CPPFLAGS $cppflags \
-              $CXXFLAGS $cxxflags \
-              -c $1 -o $basename.@OBJEXT@
-            retval=$?
-            test $retval -ne 0 && exit $retval
-            ;;
-        esac
-      else
-        for arg in $@; do
-          $program --alternate="$alternate" --compile $arg
-          retval=$?
-          test $retval -ne 0 && exit $retval
-        done
-      fi
-      exit 0
-      ;;
-    --link)
-      shift
-      progname=$1
-      shift
-      echo $compiler $LDFLAGS $ldflags -o $progname $@ $libs $LIBS \
-        | $preformat | sed "$sedformat"
-      $compiler \
-        $LDFLAGS $ldflags \
-        -o $progname $@ \
-        $libs $LIBS
-      retval=$?
-      test $retval -ne 0 && exit $retval
-      case $host in
-      *-darwin*)
-        echo "$me: making Mac OS X application"
-        mkdir $progname.app 2>/dev/null
-        mkdir $progname.app/Contents 2>/dev/null
-        mkdir $progname.app/Contents/MacOS 2>/dev/null
-        if test -d $progname.app/Contents/MacOS &&
-          mv -f $progname $progname.app/Contents/MacOS/ &&
-          echo "APPL????" >$progname.app/Contents/PkgInfo; then
-          :
-        else
-          echo >&2 "$me: failed to make Mac OS X application"
-          echo >&2 " - problem is probably user permission or disk space related"
-          exit 1
-        fi
+        sed -f $sedscript <$1 >>$outfile
+        rm -f $sedscript
+        ;;
+      *)
+        eval "VAL=\${AC_SUBST_$1}"
+        echo "$VAL"
         ;;
       esac
-      exit 0
-      ;;
-    --build)
-      shift
-      progname=$1
-      objs=
-      extraldflags=
-      extralibs=
-      shift
+    else
       for arg in $@; do
-        case $arg in
-          *.h.in)
-            $program --alternate="$alternate" --ac-subst $arg
-            ;;
-          *.c.in | *.cpp.in | *.cxx.in | *.cc.in)
-            outfile=`echo "$arg" | sed -e 's/\.in$//'`
-            basename=`echo "$outfile" | sed -e 's/\.[^\.]*$//'`  # strip off extension
-            $program --alternate="$alternate" --ac-subst $arg
-            $program --alternate="$alternate" --compile $outfile
-            retval=$?
-            test $retval -ne 0 && exit $retval
-            objs="$objs $basename.@OBJEXT@"
-            ;;
-          *.c | *.cpp | *.cxx | *.cc)
-            basename=`echo "$arg" | sed -e 's/\.[^\.]*$//'`  # strip off extension
-            $program --alternate="$alternate" --compile $arg
-            retval=$?
-            test $retval -ne 0 && exit $retval
-            objs="$objs $basename.@OBJEXT@"
-            ;;
-          -L*)
-            extraldflags="$extraldflags $arg"
-            ;;
-          -l*)
-            extralibs="$extralibs $arg"
-            ;;
-        esac
+        $program --alternate="$alternate" --ac-subst $arg
+        retval=$?
+        test $retval -ne 0 && exit $retval
       done
-      if test -z "$objs"; then
-        echo >&2 "$usage"
-        echo >&2 ""
-        echo >&2 "$me: no object files"
+    fi
+    exit 0
+    ;;
+  --ac-desubst)
+    shift
+    echo $me --ac-desubst $1
+    outfile="$1.in"
+    sedscript=/tmp/ac_subst_$$.sed
+    grep "^AC_SUBST_" $configfile \
+      | sed -e 's/^AC_SUBST_\([^=]*\)="\([^"]*\)"$/s\/\2\/@\1@\/g;/g' \
+      >$sedscript
+    sed -f $sedscript <$1 >$outfile
+    rm -f $sedscript
+    ;;
+  --compile)
+    shift
+    if test $# -eq 1; then
+      case $1 in
+      *\.in)
+        outfile=`echo $1 | sed -e 's/\.in$//'`
+        $program --alternate="$alternate" --ac-subst $1
+        $program --alternate="$alternate" --compile $outfile
+        retval=$?
+        test $retval -ne 0 && exit $retval
+        ;;
+      *)
+        basename=`echo "$1" | sed -e 's/\.[^\.]*$//'`  # strip off extension
+        echo $compiler $CPPFLAGS $cppflags $CXXFLAGS $cxxflags -c $1 -o $basename.@OBJEXT@ \
+          | $preformat | sed "$sedformat"
+        $compiler \
+          $CPPFLAGS $cppflags \
+          $CXXFLAGS $cxxflags \
+          -c $1 -o $basename.@OBJEXT@
+        retval=$?
+        test $retval -ne 0 && exit $retval
+        ;;
+      esac
+    else
+      for arg in $@; do
+        $program --alternate="$alternate" --compile $arg
+        retval=$?
+        test $retval -ne 0 && exit $retval
+      done
+    fi
+    exit 0
+    ;;
+  --link)
+    shift
+    progname=$1
+    shift
+    echo $compiler $LDFLAGS $ldflags -o $progname $@ $libs $LIBS \
+      | $preformat | sed "$sedformat"
+    $compiler \
+      $LDFLAGS $ldflags \
+      -o $progname $@ \
+      $libs $LIBS
+    retval=$?
+    test $retval -ne 0 && exit $retval
+    case $host in
+    *-darwin*)
+      echo "$me: making Mac OS X application"
+      mkdir $progname.app 2>/dev/null
+      mkdir $progname.app/Contents 2>/dev/null
+      mkdir $progname.app/Contents/MacOS 2>/dev/null
+      if test -d $progname.app/Contents/MacOS &&
+        mv -f $progname $progname.app/Contents/MacOS/ &&
+        echo "APPL????" >$progname.app/Contents/PkgInfo; then
+        :
+      else
+        echo >&2 "$me: failed to make Mac OS X application"
+        echo >&2 " - problem is probably user permission or disk space related"
         exit 1
       fi
-      echo $compiler $CPPFLAGS $cppflags $CXXFLAGS $cxxflags \
-        $LDFLAGS $ldflags $extraldflags \
-        -o $progname $objs $extralibs $libs $LIBS \
-        | $preformat | sed "$sedformat"
-      $compiler \
-        $CPPFLAGS $cppflags \
-        $CXXFLAGS $cxxflags \
-        $LDFLAGS $ldflags $extraldflags \
-        -o $progname $objs \
-        $extralibs $libs $LIBS
-      retval=$?
-      test $retval -ne 0 && exit $retval
-      case $host in
-      *-darwin*)
-        echo "$me: making Mac OS X application"
-        mkdir $progname.app 2>/dev/null
-        mkdir $progname.app/Contents 2>/dev/null
-        mkdir $progname.app/Contents/MacOS 2>/dev/null
-        if test -d $progname.app/Contents/MacOS &&
-          mv -f $progname $progname.app/Contents/MacOS/ &&
-          echo "APPL????" >$progname.app/Contents/PkgInfo; then
-          :
-        else
-          echo >&2 "$me: failed to make Mac OS X application"
-          echo >&2 " - problem is probably user permission or disk space related"
-          exit 1
-        fi
+      ;;
+    esac
+    exit 0
+    ;;
+  --build)
+    shift
+    progname=$1
+    objs=
+    extraldflags=
+    extralibs=
+    shift
+    for arg in $@; do
+      case $arg in
+      *.h.in)
+        $program --alternate="$alternate" --ac-subst $arg
+        ;;
+      *.c.in | *.cpp.in | *.cxx.in | *.cc.in)
+        outfile=`echo "$arg" | sed -e 's/\.in$//'`
+        basename=`echo "$outfile" | sed -e 's/\.[^\.]*$//'`  # strip off extension
+        $program --alternate="$alternate" --ac-subst $arg
+        $program --alternate="$alternate" --compile $outfile
+        retval=$?
+        test $retval -ne 0 && exit $retval
+        objs="$objs $basename.@OBJEXT@"
+        ;;
+      *.c | *.cpp | *.cxx | *.cc)
+        basename=`echo "$arg" | sed -e 's/\.[^\.]*$//'`  # strip off extension
+        $program --alternate="$alternate" --compile $arg
+        retval=$?
+        test $retval -ne 0 && exit $retval
+        objs="$objs $basename.@OBJEXT@"
+        ;;
+      -L*)
+        extraldflags="$extraldflags $arg"
+        ;;
+      -l*)
+        extralibs="$extralibs $arg"
         ;;
       esac
-      exit 0
-      ;;
-    --setup)
-      # FIXME: scan variables and only modify variables that need modification
-      echo "PATH=\$PATH:$prefix/bin"
-      echo "LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:$prefix/lib"
-      echo "export PATH LD_LIBRARY_PATH"
-      exit 0
-      ;;
-    --setup-front)
-      # FIXME: scan variables and only modify variables that need modification
-      echo "PATH=$prefix/bin:\$PATH"
-      echo "LD_LIBRARY_PATH=$prefix/lib:\$LD_LIBRARY_PATH"
-      echo "export PATH LD_LIBRARY_PATH"
-      exit 0
-      ;;
-    # ignore some options
-    --alternate=*) ;;
-    --debug) ;;
-    # args not catched until now are invalid
-    *)
-      echo >&2 "$me: Invalid option: \"$1\""
+    done
+    if test -z "$objs"; then
       echo >&2 "$usage"
+      echo >&2 ""
+      echo >&2 "$me: no object files"
       exit 1
+    fi
+    echo $compiler $CPPFLAGS $cppflags $CXXFLAGS $cxxflags \
+      $LDFLAGS $ldflags $extraldflags \
+      -o $progname $objs $extralibs $libs $LIBS \
+      | $preformat | sed "$sedformat"
+    $compiler \
+      $CPPFLAGS $cppflags \
+      $CXXFLAGS $cxxflags \
+      $LDFLAGS $ldflags $extraldflags \
+      -o $progname $objs \
+      $extralibs $libs $LIBS
+    retval=$?
+    test $retval -ne 0 && exit $retval
+    case $host in
+    *-darwin*)
+      echo "$me: making Mac OS X application"
+      mkdir $progname.app 2>/dev/null
+      mkdir $progname.app/Contents 2>/dev/null
+      mkdir $progname.app/Contents/MacOS 2>/dev/null
+      if test -d $progname.app/Contents/MacOS &&
+        mv -f $progname $progname.app/Contents/MacOS/ &&
+        echo "APPL????" >$progname.app/Contents/PkgInfo; then
+        :
+      else
+        echo >&2 "$me: failed to make Mac OS X application"
+        echo >&2 " - problem is probably user permission or disk space related"
+        exit 1
+      fi
       ;;
+    esac
+    exit 0
+    ;;
+  --setup)
+    # FIXME: scan variables and only modify variables that need modification
+    echo "PATH=\$PATH:$prefix/bin"
+    echo "LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:$prefix/lib"
+    echo "export PATH LD_LIBRARY_PATH"
+    exit 0
+    ;;
+  --setup-front)
+    # FIXME: scan variables and only modify variables that need modification
+    echo "PATH=$prefix/bin:\$PATH"
+    echo "LD_LIBRARY_PATH=$prefix/lib:\$LD_LIBRARY_PATH"
+    echo "export PATH LD_LIBRARY_PATH"
+    exit 0
+    ;;
+  --header)
+    shift
+    classname=$1
+    for header in `find ${prefix}/include/Inventor -type f | xargs grep -n "^class SO@GUI@_DLL_API ${classname}\>" | cut -d: -f1`; do
+      echo "FILE: ${header}"
+      cat "${header}"
+    done
+    exit 0
+    ;;
+  # ignore some options
+  --alternate=*) ;;
+  --debug) ;;
+  # args not catched until now are invalid
+  *)
+    echo >&2 "$me: Invalid option: \"$1\""
+    echo >&2 "$usage"
+    exit 1
+    ;;
   esac
   shift
 done
 
 exit 0
+
